---
- name: install nginx and roundcube dependencies
  yum:
    name:
      - keepalived
      - nginx
      - php
      - php-fpm
      - php-mysql
      - php-pear
      - php-mcrypt
      - php-intl
      - php-ldap
      - php-pear-Net-SMTP
      - php-pear-Net-IDNA2
      - php-pear-Mail-Mime
    state: latest
- name: copy nginx.conf
  copy: src=../files/nginx.conf dest=/etc/nginx/nginx.conf state=present

- name: copy nginx default.conf
  copy: src=../files/default.conf  dest=/etc/nginx/conf.d/default.conf state=present

- name: copy php-fpm config
  copy: src=../files/www.conf  dest=/etc/php-fpm.d/www.conf state=present

- name: create directory for roundcube
  file: path=/usr/share/nginx/html/webmail state=directory mode=0755

- name: copy roundcube script directory
  copy: src=../files/roundcubemail dest=/usr/share/nginx/html/webmail/ state=present


